### ISSUE TITLE
The version for mac m1 devices is too low

### ISSUE THREAD

**Issue by zhuolinzhang** [conda-forge/uproot-feedstock#100]
- [✓] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Hi, I use a MacBook Pro 13.3 M1 version now. I tried to install the uproot by conda. But only uproot 4.0.0 can be installed. Then, I tried to run my script, the output is quite strange and different from the output from another notebook. The uproot version is higher in that notebook. It seems like a bug in uproot 4.0.0. So the uproot 4.0.0 in my MacBook was removed, and uproot 4.1.7 was installed by pip in a virtual conda environment. This time the output is the same as in another device. 

The uproot 4.1.7 installed by pip seems like works well. But I hope I can install the newer uproot by conda. Could the uproot for OSX-arm64 be updated? 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
conda 4.10.3 installed by Miniforge3-MacOSX-arm64

```
</details>

**Comment by henryiii** [comment]
This should be no-arch, so it should not depend on OS or architecture. I'm on vacation and won't be near an M1 till next week.

**Comment by chrisburr** [comment]
This will be fixed by https://github.com/conda-forge/uproot-feedstock/pull/98 within the next day.

> This should be no-arch

`uproot-base` is noarch, `uproot` also depends on `xrootd` which isn't available for Windows so it becomes platform specific due to having different dependencies (it was once supported it but it's been unmaintained for many years and is now full of POSIX-isms last time I tried).
